jobs:
  - name: test
    plan:
    - get: pull-request
      trigger: true
      version: every
    - put: pull-request
      params:
        path: pull-request
        context: build
        status: pending
    - task: placeholder
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: alpine, tag: "3.5"}
        run:
          path: /bin/sh
          args:
            - -xce
            - |
              sleep 30
              echo "HELLO, WORLD!"
    - put: pull-request
      params:
        path: pull-request
        context: build
        status: success

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: itsdalmo/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 1m
    source:
      repository: itsdalmo/test-repository
      context: concourse-ci/status
      access_token: ((github-access-token))
